import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { Employees } from './api/employees'
import { Wizard } from './components/Wizard'

const Home: NextPage = () => {

  const [employees, setEmployees] = useState<Employees[]>([])

  useEffect(() => {
    async function getData() {
      const response = await fetch(
        `/api/employees`
      )
      let actualData = await response.json();
      setEmployees(actualData.employees)
    }
    getData()
  }, [])

  //@ts-ignore
  const onClick = async (e, employeeToUpdate) => {
    const data = await fetch(`/api/employees/${employeeToUpdate.id}`, {
      method: 'PATCH',
      body: JSON.stringify({
        status: e.target.text
      })
    })
    let response = await data.json();
    setEmployees(response.employees)
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Employee Management System V0.1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Employee Management System V0.1
        </h1>

        <div className={styles.grid}>
          <div className="card">
            <Wizard employees={employees} onClick={onClick} />
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
