import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { Employees } from './api/employees'
import { Wizard } from './components/Wizard'

const Home: NextPage = () => {

  const [employees, setEmployees] = useState<Employees[]>([])

  useEffect(() => {
    async function getData() {
      const response = await fetch(
        `/api/employees`
      )
      let actualData = await response.json();

      console.log(actualData)
      setEmployees(actualData.employees)
    }
    getData()
  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Employee Management System V0.1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Employee Management System V0.1
        </h1>

        <div className={styles.grid}>
          { /* employees.length !== 0 && employees.map(employee => {
            return <div className="card">
              <h2>{employee.name}</h2>
              <p>{employee.status}</p>
            </div>
          }) */ }
          <div className="card">
            <Wizard employees={employees} />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
